env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - simple-import-sort
rules:
  array-bracket-spacing:
    - error
    - never
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-undef: 0
  no-trailing-spaces:
    - error
    - ignoreComments: true
      skipBlankLines: true
  semi:
    - error
    - always
  semi-spacing:
    - error
    - after: true
      before: false
  semi-style:
    - error
    - last
  simple-import-sort/imports:
    - error
